apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: oomkill-protector
  name: protector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oomkill-protector
  namespace: protector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: oomkill-protector
    namespace: protector
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oomkill-protector
  namespace: protector
  labels:
    control-plane: oomkill-protector
spec:
  selector:
    matchLabels:
      control-plane: oomkill-protector
  template:
    metadata:
      labels:
        control-plane: oomkill-protector
    spec:
      containers:
      - command:
        - /oomkill-protector
        image: registry.gz.cvte.cn/nic/oomkill-protector:latest
        name: protector
        env:
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: dockersock
          - mountPath: /sys/fs/cgroup
            name: cgroup
      terminationGracePeriodSeconds: 10
      serviceAccountName: "oomkill-protector"
      hostPID: true
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
